# Use the Node.js 18 base image
FROM node:18

# Set the working directory to the app directory
WORKDIR .

# Copy package.json and package-lock.json and install dependencies
COPY package*.json ./

RUN npm install
# Copy the application files to the container's app directory
COPY . .

# Install nodemon globally
RUN npm install -g nodemon

EXPOSE 8080

# Start the Node.js application using nodemon
CMD ["npm", "start"]

